import argparse
import time
from typing import List
import os

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Check logs generated by the kernel for specific messages")
    parser.add_argument("kernel.log", help="Path to kernel logs")
    args: argparse.Namespace = parser.parse_args()
    kernel_log_path: str = getattr(args, "kernel.log")
    start = time.time()
    while True:
        passed = time.time() - start
        content: str = ""
        if os.path.isfile(kernel_log_path):
            with open(kernel_log_path, "r") as f:
                content = f.read()
        if len(content) > 0:
            if content[-1] == "\0":
                content = content[:-1]
            if content[-1] == "\n":
                content = content[:-1]
        success_messages = content.count("kernel was initialized successfully!")
        init_messages = content.count("kernel is initializing...")
        if init_messages == 1 and success_messages == 1:
            if passed > 0.3:
                print(content)
                print(f"\033[32mPASSED\033[0m")
                exit(0)
        elif init_messages == 0 and success_messages == 1:
            print(content)
            print(f"\033[31mFAILED\033[0m: success message appeared before init message")
            exit(1)
        elif init_messages == 1 and success_messages == 0:
            if passed > 1:
                print(content)
                print(f"\033[31mFAILED\033[0m: kernel initialization failed: success log didn't appear in {passed:.1f}s while init log appeared")
                exit(1)
        elif init_messages == 0 and success_messages == 0:
            if passed > 1:
                print(content)
                print(f"\033[31mFAILED\033[0m: kernel init log didn't appear {passed:.1f}s")
                exit(1)
        elif init_messages > 1 and success_messages > 1:
            print(content)
            print(f"\033[31mFAILED\033[0m: messages are doubled, did reboot happened?")
            exit(1)
        time.sleep(0.05)
